enc_id = '000odFDd2M/+G74dQLnQI9oYwJhXk+YCwzZQ=='
password = '00e5s69iRv1jvASDlWpQ227u1fxCx8OXM1'
salt = 'mp3z6h'
key_pair = [
    [
    153,
    171,
    234,
    102,
    181,
    101,
    124,
    49,
    185,
    118,
    56,
    62,
    225,
    192,
    52,
    170,
    198,
    28,
    0,
    133,
    84,
    104,
    125,
    184,
    241,
    89,
    182,
    237,
    190,
    120,
    74,
    129,
    150,
    158,
    43,
    242,
    170,
    44,
    103,
    186,
    240,
    206,
    85,
    185,
    195,
    7,
    72,
    39,
    24,
    108,
    151,
    203,
    39,
    92,
    154,
    175,
    201,
    200,
    9,
    198,
    53,
    25,
    238,
    250,
],
    [
    150,
    158,
    43,
    242,
    170,
    44,
    103,
    186,
    240,
    206,
    85,
    185,
    195,
    7,
    72,
    39,
    24,
    108,
    151,
    203,
    39,
    92,
    154,
    175,
    201,
    200,
    9,
    198,
    53,
    25,
    238,
    250,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
"91.98.29.119:21116" = true
